import streamlit as st
import plotly.express as px

from config import APP_TITLE
from utils.layout import render_page, end_page
from utils.helpers import section_title
from utils.data_loader import load_dashboard_data


# ==========================================================
# Page Configuration
# ==========================================================

st.set_page_config(
    page_title=f"Fleet Health | {APP_TITLE}",
    layout="wide",
)

render_page(
    "Fleet Health Dashboard",
    (
        "Monitor fleet condition, identify maintenance priorities "
        "and support proactive engineering decisions using AI predictions."
    ),
)


# ==========================================================
# Load Fleet Prediction Data
# ==========================================================

dashboard_df = load_dashboard_data()


# ==========================================================
# Dashboard Overview
# ==========================================================

st.info(
    """
The Fleet Health Dashboard presents fleet-level predictions generated by the
**Improved LSTM** using the NASA C-MAPSS FD001 dataset.

Rather than assessing only one engine, this dashboard combines Remaining
Useful Life predictions, health classifications, risk levels and maintenance
recommendations across the complete fleet.

Its purpose is to help maintenance engineers and managers identify engines
requiring attention and support proactive, human-centred maintenance planning.
"""
)


# ==========================================================
# 1. Fleet Overview
# ==========================================================

section_title("1. Fleet Overview")

total_engines = dashboard_df["engine_id"].nunique()

healthy = (
    dashboard_df["health_status"] == "Healthy"
).sum()

warning = (
    dashboard_df["health_status"] == "Warning"
).sum()

critical = (
    dashboard_df["health_status"] == "Critical"
).sum()

avg_rul = dashboard_df[
    "predicted_rul_lstm"
].mean()

overview_col1, overview_col2, overview_col3, overview_col4 = (
    st.columns(4)
)

overview_col1.metric(
    "Total Engines",
    total_engines,
)

overview_col2.metric(
    "Healthy",
    healthy,
)

overview_col3.metric(
    "Warning",
    warning,
)

overview_col4.metric(
    "Critical",
    critical,
)

st.metric(
    "Average Predicted Remaining Useful Life",
    f"{avg_rul:.2f} cycles",
)

st.divider()


# ==========================================================
# 2. Fleet Health Distribution
# ==========================================================

section_title("2. Fleet Health Distribution")

health_counts = (
    dashboard_df["health_status"]
    .value_counts()
    .reset_index()
)

health_counts.columns = [
    "Health Status",
    "Count",
]

fig_health = px.pie(
    health_counts,
    names="Health Status",
    values="Count",
    hole=0.55,
    title="Fleet Health Classification",
    color="Health Status",
    color_discrete_map={
        "Healthy": "#2E8B57",
        "Warning": "#87CEFA",
        "Critical": "#DC143C",
    },
)

fig_health.update_traces(
    textposition="inside",
    textinfo="percent+label",
)

st.plotly_chart(
    fig_health,
    use_container_width=True,
)

st.caption(
    """
    Fleet health status is derived from the predicted Remaining Useful Life
    and translated into operational categories for maintenance planning.
    """
)

st.divider()


# ==========================================================
# 3. Remaining Useful Life Distribution
# ==========================================================

section_title("3. Remaining Useful Life Distribution")

fig_rul = px.histogram(
    dashboard_df,
    x="predicted_rul_lstm",
    nbins=20,
    title="Distribution of Predicted Remaining Useful Life",
)

fig_rul.update_layout(
    xaxis_title="Predicted Remaining Useful Life (Cycles)",
    yaxis_title="Number of Engines",
)

st.plotly_chart(
    fig_rul,
    use_container_width=True,
)

st.caption(
    """
    The histogram shows how the predicted Remaining Useful Life values are
    distributed across the fleet. Engines located toward the lower end of
    the distribution require earlier engineering attention.
    """
)

st.divider()


# ==========================================================
# 4. Engines Requiring Immediate Attention
# ==========================================================

section_title("4. Engines Requiring Immediate Attention")

priority_df = (
    dashboard_df
    .sort_values("predicted_rul_lstm")
    .head(10)
    .copy()
)

priority_display_df = priority_df[
    [
        "engine_id",
        "predicted_rul_lstm",
        "health_status",
        "risk_level",
        "recommendation",
    ]
].copy()

priority_display_df.columns = [
    "Engine ID",
    "Predicted RUL",
    "Health Status",
    "Risk Level",
    "Recommendation",
]

st.dataframe(
    priority_display_df,
    use_container_width=True,
    hide_index=True,
)

st.caption(
    """
    Engines are ranked from the lowest to the highest predicted Remaining
    Useful Life so that the most urgent maintenance cases appear first.
    """
)

st.divider()


# ==========================================================
# 5. Fleet Interpretation
# ==========================================================

section_title("5. Fleet Interpretation")

if total_engines > 0:
    critical_pct = (
        critical / total_engines
    ) * 100

    warning_pct = (
        warning / total_engines
    ) * 100

    healthy_pct = (
        healthy / total_engines
    ) * 100

else:
    critical_pct = 0.0
    warning_pct = 0.0
    healthy_pct = 0.0

st.info(
    f"""
### Fleet-Level Decision Support

The deployed **Improved LSTM** analysed **{total_engines} engines**
within the fleet.

Current fleet condition:

- **Healthy:** {healthy} engines ({healthy_pct:.1f}%)
- **Warning:** {warning} engines ({warning_pct:.1f}%)
- **Critical:** {critical} engines ({critical_pct:.1f}%)

The fleet dashboard transforms individual Remaining Useful Life predictions
into actionable maintenance intelligence.

Maintenance engineers and managers can use these results to:

- prioritise engine inspections;
- schedule maintenance according to operational urgency;
- reduce the likelihood of unexpected equipment failure;
- improve operational availability;
- support evidence-based engineering decisions.

The dashboard therefore supports human-centred predictive maintenance by
helping technical personnel interpret and act on AI-generated results rather
than replacing professional engineering judgement.
"""
)

st.divider()


# ==========================================================
# 6. Prediction Summary for All Engines
# ==========================================================

section_title("6. Prediction Summary for All Engines")

all_engines_df = dashboard_df[
    [
        "engine_id",
        "predicted_rul_lstm",
        "health_status",
        "risk_level",
        "recommendation",
    ]
].copy()

all_engines_df = all_engines_df.sort_values(
    "predicted_rul_lstm"
)

all_engines_df.columns = [
    "Engine ID",
    "Predicted RUL",
    "Health Status",
    "Risk Level",
    "Recommendation",
]

st.dataframe(
    all_engines_df,
    use_container_width=True,
    hide_index=True,
)

st.caption(
    """
    The full fleet table provides an operational view of every engine,
    ordered by predicted Remaining Useful Life.
    """
)

st.divider()


# ==========================================================
# 7. Explainability Reference
# ==========================================================

section_title("7. Explainability Reference")

st.success(
    """
Fleet-level predictions are generated by the **Improved LSTM**.

To investigate why the model produced a particular prediction, open the
**Explainability** page.

The Explainability module provides:

- TimeSHAP feature attribution;
- TimeSHAP event attribution;
- temporal coalition pruning;
- Integrated Gradients validation;
- critical degradation-window identification;
- sensor-time attribution;
- feature-deletion faithfulness analysis.

Together, these explanation methods improve transparency, support user trust
and help maintenance personnel make informed engineering decisions.
"""
)


# ==========================================================
# Page Footer
# ==========================================================

end_page()